name: Retweet epitwitter
'on':
  push:
    branches:
      - master
#  schedule:
#    - cron:  '*/3 * * * *'

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - name: Install Package Dependencies
        run: |-
          Rscript -e "install.packages('remotes')"
          Rscript -e "remotes::install_deps(dependencies = TRUE)"
      - name: Run epibot script
        run: |-
          Rscript -e "source('R/epibot.R')"
      - name: Commit results
        run: |
          git commit -m "Update data" -a
          git push https://${{github.actor}}:${{secrets.GITHUB_TOKEN}}@github.com/${{github.repository}}.git HEAD:${{ github.ref }}
